---
version: "3.8"

x-splunk-def: &splunk-def
  image: splunk/splunk:8.2
  container_name: splunk
  environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_PASSWORD=quickstart
    - SPLUNK_APPS_URL=https://github.com/splunkdlt/splunk-app-quorum/releases/download/1.0.7/splunk-app-quorum-v1.0.7.tgz
  ports:
    - 8000:8000
    - 8088:8088
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000"]
    interval: 5s
    timeout: 5s
    retries: 20
  volumes:
    - ./splunk/splunk.yml:/tmp/defaults/default.yml
    - splunk:/opt/splunk/var

x-tessera-def: &tessera-def
  image: quorumengineering/tessera:${TESSERA_VERSION:-latest}
  expose:
    - 9000
    - 9080
    - 9101
  healthcheck:
    test:
      [
        "CMD",
        "wget",
        "--spider",
        "--proxy",
        "off",
        "http://localhost:9000/upcheck",
      ]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir -p /var/log/tessera;
      mkdir -p /data/tm;
      cp /config/keys/tm.* /data/tm;
      CONFIG_PLOOP=$$(cat /data/tm/tm.key);
      CONFIG_PUBLICKEY=$$(cat /data/tm/tm.pub);
      sed -e 's|'config_ploop'|'"$$CONFIG_PLOOP"'|g' -e 's|'config_publickey'|'"$$CONFIG_PUBLICKEY"'|g' -e 's|'NETWORK_ADDRESS_TESSERA'|'"$$NETWORK_ADDRESS_TESSERA"'|g' /config/logs/tessera-settings.txt >> /data/tm/tessera-config-09.json;
      /tessera/bin/tessera -configfile /data/tm/tessera-config-09.json &> /var/log/tessera/tessera-$$HOSTNAME.log | tee -a /var/log/tessera/tessera-$$HOSTNAME.log;
x-otelcollector-def: &otelcollector-def
  image: quay.io/signalfx/splunk-otel-collector:0.26.0
  container_name: otelcollector
  depends_on:
    - splunk
  command:
    - --config
    - /etc/otel/config.yaml
  volumes:
    - ./splunk/otel-collector-config.yml:/etc/otel/config.yaml
    - /var/log:/var/log
    - ./logs/tessera:/var/log-tessera
    - ./logs/quorum:/var/log-quorum
  environment:
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_ACCESS_TOKEN=disable # You can use this option to send data to Splunk Cloud.
    - SPLUNK_REALM=disable # You can use this option to send data to Splunk Cloud.

x-ethlogger-def: &ethlogger-def
  image: ghcr.io/splunkdlt/ethlogger:3.0.1
  container_name: ethlogger
  environment:
    - COLLECT_PEER_INFO=true
    - COLLECT_PENDING_TX=true
    - ETH_RPC_URL=http://rpcnode:8545
    - NETWORK_NAME=quickstart
    - START_AT_BLOCK=latest
    - SPLUNK_HEC_URL=https://splunk:8088
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_EVENTS_INDEX=ledger
    - SPLUNK_METRICS_INDEX=metrics
    - SPLUNK_INTERNAL_INDEX=metrics
    - SPLUNK_HEC_REJECT_INVALID_CERTS=false
    - ABI_DIR=/app/abis
    - DEBUG=ethlogger:platforms,ethlogger:eth
  volumes:
    - ethlogger:/app
    - ./smart_contracts/contracts:/app/abis
  depends_on:
    - splunk
  restart: unless-stopped

x-quorum-def: &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      mkdir -p /config /data /var/log/quorum;
      cp /quorum/passwords.txt /config/passwords.txt
      cp "/quorum/${GOQUORUM_CONS_ALGO}Genesis.json" /config/genesis.json
      cp -r /quorum/* /data;
      geth --datadir=/data init /config/genesis.json;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth \
      --datadir /data \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full --nousb \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_API \
      --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_API \
      --port 30303 \
      --identity node$${NODE_ID}-$${GOQUORUM_CONS_ALGO} \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log
x-quorum-member-def: &quorum-member-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      /quorum/tools/wait-for $$QUORUM_PTM_URL -- echo "bloooop!"
      mkdir -p /config /data/dd /var/log/quorum;
      cp /quorum/passwords.txt /config/passwords.txt
      cp "/quorum/${GOQUORUM_CONS_ALGO}Genesis.json" /config/genesis.json
      cp -r /quorum/* /data/dd/;
      geth --datadir=/data/dd init /config/genesis.json;
      cp /config/keys/accountkey /data/dd/keystore/key;
      cp /config/keys/nodekey /data/dd/geth/nodekey;
      geth \
      --datadir /data/dd \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_API \
      --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_API \
      --port 30303 \
      --identity node$${NODE_ID}-$${GOQUORUM_CONS_ALGO} \
      --ptm.url $${QUORUM_PTM_URL} --ptm.timeout 5  --ptm.http.writebuffersize 4096 --ptm.http.readbuffersize 4096 --ptm.tls.mode off \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$(hostname -i).log
services:
  entrypointAPI:
    image: elixir

  validator1:
    <<: *quorum-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator1:/config/keys
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    <<: *quorum-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=2
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator2:/config/keys
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    <<: *quorum-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=3
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator3:/config/keys
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    <<: *quorum-def
    ports:
      - 22004:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=4
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator4:/config/keys
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    <<: *quorum-def
    container_name: rpcnode
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=5
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/rpcnode:/config/keys
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.15

  member1tessera:
    <<: *tessera-def
    ports:
      - 9081:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=6
      - JAVA_OPTS="-Dlogback.configurationFile=/config/logs/logback.xml"
      - NETWORK_ADDRESS_TESSERA=172.16.239.26
    volumes:
      - ./config/tessera:/config/logs
      - ./config/nodes/member1:/config/keys
      - member1volume:/data
      - ./logs/tessera:/var/log/tessera
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.26

  member1quorum:
    <<: *quorum-member-def
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member1tessera
      - rpcnode
    environment:
      - NODE_ID=6
      - QUORUM_PTM_URL=http://172.16.239.26:9101
      - NETWORK_ADDRESS_TESSERA=172.16.239.26
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/member1:/config/keys
      - member1volume:/data
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.16

  member2tessera:
    <<: *tessera-def
    ports:
      - 9082:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=7
      - JAVA_OPTS="-Dlogback.configurationFile=/config/logs/logback.xml"
      - NETWORK_ADDRESS_TESSERA=172.16.239.27
    volumes:
      - ./config/tessera:/config/logs
      - ./config/nodes/member2:/config/keys
      - member2volume:/data
      - ./logs/tessera:/var/log/tessera
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.27

  member2quorum:
    <<: *quorum-member-def
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member2tessera
      - rpcnode
    environment:
      - NODE_ID=7
      - QUORUM_PTM_URL=http://172.16.239.27:9101
      - NETWORK_ADDRESS_TESSERA=172.16.239.27
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/member2:/config/keys
      - member2volume:/data
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.17

  member3tessera:
    <<: *tessera-def
    ports:
      - 9083:9080
    environment:
      - TESSERA_CONFIG_TYPE="-09"
      - NODE_ID=8
      - JAVA_OPTS="-Dlogback.configurationFile=/config/logs/logback.xml"
      - NETWORK_ADDRESS_TESSERA=172.16.239.28
    volumes:
      - ./config/tessera:/config/logs
      - ./config/nodes/member3:/config/keys
      - member3volume:/data
      - ./logs/tessera:/var/log/tessera
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.28

  member3quorum:
    <<: *quorum-member-def
    ports:
      - 20004:8545/tcp
      - 20005:8546/tcp
      - 30303
      - 9545
    depends_on:
      - member3tessera
      - rpcnode
    environment:
      - NODE_ID=8
      - QUORUM_PTM_URL=http://172.16.239.28:9101
      - NETWORK_ADDRESS_TESSERA=172.16.239.28
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/member3:/config/keys
      - member3volume:/data
      - ./logs/quorum:/var/log/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.18

  node_compiler:
    image: node
    restart: "on-failure"
    ports:
      - 8080
    volumes:
      - ./node_compiler_install:/node_compiler
    command: node app.js
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.60

  otelcollector:
    <<: *otelcollector-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.36

  splunk:
    <<: *splunk-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35

  ethlogger:
    <<: *ethlogger-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.37

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --docker_only=true
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.38
networks:
  quorum-dev-quickstart:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

volumes:
  member1volume:
  member2volume:
  member3volume:
  splunk:
  ethlogger: