apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  labels:
    io.kompose.service: validator1
  name: validator1
spec:
  ports:
    - name: "21001"
      port: 21001
      targetPort: 8545
    - name: "30303"
      port: 30303
      targetPort: 30303
    - name: "9545"
      port: 9545
      targetPort: 9545
    - name: 30303-tcp
      port: 30303
      targetPort: 30303
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: 9545-tcp
      port: 9545
      targetPort: 9545
  selector:
    io.kompose.service: validator1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: validator1-claim2
  name: validator1-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: validator1-claim1
  name: validator1-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: validator1-claim0
  name: validator1-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (HEAD)
  labels:
    io.kompose.network/quorum-dev-quickstart: "true"
    io.kompose.service: validator1
  name: validator1
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - |
          mkdir -p /config /data /var/log/quorum;
          cp /quorum/passwords.txt /config/passwords.txt
          cp "/quorum/Genesis.json" /config/genesis.json
          cp -r /quorum/* /data;
          geth --datadir=/data init /config/genesis.json;
          cp /config/keys/accountkey /data/keystore/key;
          cp /config/keys/nodekey /data/geth/nodekey;
          geth \
          --datadir /data \
          --nodiscover \
          --permissioned \
          --verbosity 5 \
          $CONSENSUS_ARGS \
          --syncmode full --nousb \
          --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
          --networkid ${QUORUM_NETWORK_ID:-1337} \
          --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$QUORUM_API \
          --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$QUORUM_API \
          --port 30303 \
          --identity node${NODE_ID}-${GOQUORUM_CONS_ALGO} \
          --unlock 0 \
          --allow-insecure-unlock \
          --password /config/passwords.txt \
          &> /var/log/quorum/geth-$HOSTNAME-$(hostname -i).log | tee -a /var/log/quorum/geth-$HOSTNAME-$(hostname -i).log
      env:
        - name: NODE_ID
          value: "1"
        - name: PRIVATE_CONFIG
          value: ignore
      image: quorumengineering/quorum:latest
      livenessProbe:
        exec:
          command:
            - wget
            - --spider
            - --proxy
            - "off"
            - http://localhost:8545
        failureThreshold: 10
        initialDelaySeconds: 5
        periodSeconds: 3
        timeoutSeconds: 3
      name: validator1
      ports:
        - containerPort: 8545
        - containerPort: 30303
        - containerPort: 9545
      resources: {}
      volumeMounts:
        - mountPath: /quorum
          name: validator1-claim0
        - mountPath: /config/keys
          name: validator1-claim1
        - mountPath: /var/log/quorum
          name: validator1-claim2
  restartPolicy: OnFailure
  volumes:
    - name: validator1-claim0
      persistentVolumeClaim:
        claimName: validator1-claim0
    - name: validator1-claim1
      persistentVolumeClaim:
        claimName: validator1-claim1
    - name: validator1-claim2
      persistentVolumeClaim:
        claimName: validator1-claim2
status: {}